name = "HAMdetector_registry"
uuid = "4094375c-088a-412d-88ad-4e94234dd202"
repo = "https://github.com/HAMdetector/HAMdetector_registry.git"
description = "Registry for HAMdetector"

[packages]
eecc378a-c28e-5a81-8849-a983a4161162 = { name = "CmdStanBinaries_jll", path = "C/CmdStanBinaries_jll" }
