name = "HAMdetector_registry"
uuid = "4094375c-088a-412d-88ad-4e94234dd202"
repo = "https://github.com/HAMdetector/HAMdetector_registry.git"
description = "Registry for HAMdetector"

[packages]
17760cec-3789-11e9-196f-659854311368 = { name = "Loo", path = "L/Loo" }
42556b90-06fa-5035-9d39-4d53cd3bfd44 = { name = "HAMdetector_model_binaries_jll", path = "H/HAMdetector_model_binaries_jll" }
43212305-17f8-588b-b284-440d77d456cb = { name = "raxml_ng_jll", path = "R/raxml_ng_jll" }
e89815f6-a2f7-11e8-0a3f-6d3140f294c6 = { name = "StanInterface", path = "S/StanInterface" }
eecc378a-c28e-5a81-8849-a983a4161162 = { name = "CmdStanBinaries_jll", path = "C/CmdStanBinaries_jll" }
